"""Initial Migration

Revision ID: 06a2d78c1939
Revises: 
Create Date: 2021-06-24 14:12:26.848620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06a2d78c1939'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_posts_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'posts_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('posts_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_posts_id_fkey', 'users', 'posts', ['posts_id'], ['id'])
    # ### end Alembic commands ###
